file_format: "1"
id: cornez
name: cornez
type: keyboard
url: N/A
arch: arm
requires: [nice!nano_V2]
exposes: [pro_micro]
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
features:
  - keys
  - display
  - underglow
  - rgb
  - 5-way switch
outputs:
  - usb
  - ble
siblings:
  - cornez_left
  - cornez_right